<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net462;net8.0-windows;net10.0-windows</TargetFrameworks>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
        <OutputType>Exe</OutputType>
        <ApplicationIcon />
        <StartupObject />
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\OxyPlot\OxyPlot.csproj" />
    </ItemGroup>
</Project>
