<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>12</LangVersion>
        <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
        <Description>OxyPlot is a plotting library for .NET. This is package is based on SixLabors.ImageSharp.</Description>
        <PackageTags>plotting plot charting chart imagesharp</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningsAsErrors />
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
        <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.4" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\OxyPlot\OxyPlot.csproj" />
    </ItemGroup>
</Project>
