<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net462;net481;net6.0;net8.0;</TargetFrameworks>
        <PackageId>OxyPlot.Core</PackageId>
        <Description>OxyPlot is a plotting library for .NET. This is the core library including the foundation classes and plot model. To display the plots, you also need to add a platform-specific OxyPlot package that contains a PlotView component.</Description>
        <PackageTags>plotting plot charting chart</PackageTags>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <SignAssembly>true</SignAssembly>
        <AssemblyOriginatorKeyFile>OxyPlot.snk</AssemblyOriginatorKeyFile>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <LangVersion>9</LangVersion>
        <NoWarn>$(NoWarn);CS0618</NoWarn>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
      <WarningLevel>4</WarningLevel>
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
      <WarningLevel>4</WarningLevel>
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
      <WarningLevel>4</WarningLevel>
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
      <WarningLevel>4</WarningLevel>
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
      <WarningLevel>4</WarningLevel>
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
      <WarningLevel>4</WarningLevel>
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net462|AnyCPU'">
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net481|AnyCPU'">
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net462|AnyCPU'">
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net481|AnyCPU'">
      <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <None Include="OxyPlot.snk" />
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Axes\Probability Axis Support\" />
    </ItemGroup>
</Project>