<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0-windows;net10.0-windows</TargetFrameworks>
    <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\OxyPlot.WindowsForms\OxyPlot.WindowsForms.csproj" />
    <ProjectReference Include="..\..\..\OxyPlot\OxyPlot.csproj" />
    <ProjectReference Include="..\..\ExampleLibrary\ExampleLibrary.csproj" />
  </ItemGroup>
</Project>