<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net462;net8.0-windows;net10.0-windows</TargetFrameworks>
        <AllowMissingPrunePackageData>true</AllowMissingPrunePackageData>
        <UseWPF>true</UseWPF>
        <LangVersion>14</LangVersion>
        <Description>OxyPlot WPF unit tests</Description>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Examples\ExampleLibrary\ExampleLibrary.csproj" />
        <ProjectReference Include="..\OxyPlot\OxyPlot.csproj" />
        <ProjectReference Include="..\OxyPlot.Wpf\OxyPlot.Wpf.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
        <PackageReference Include="NSubstitute" Version="5.3" />
        <PackageReference Include="NUnit" Version="4.5.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="6.2.0" />
    </ItemGroup>
</Project>
